# Generated by Django 2.1.7 on 2019-03-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0002_auto_20190324_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('bet_type', models.CharField(choices=[('WIN', 'Win'), ('PLACE', 'Place'), ('SHOW', 'Show')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jockey', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=200)),
                ('start_position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.Horse'),
        ),
        migrations.AddField(
            model_name='bet',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.People'),
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('person', 'horse', 'bet_type')},
        ),
    ]
